Add API to send message to a chosen LLM
ls1intum/Pyris pull request #1
Opened 2023-06-16 01:34 UTC by dakennguyen

### Description
The Iris chatbot on Artermis wants to use different LLMs to answer students' questions. [**guidance**](https://github.com/microsoft/guidance) is a great tool to manage and control different LLM models at ease, but it is only offered in python package. Therefore, we initialize this project to act as a bridge between Artemis and guidance

2023-06-16 09:37 UTC, Mtze commented
Can you provide a bit more details what this PR is implementing? Maybe even share your current idea of the Iris architecture? Otherwise giving valuable feedback is difficult for me/us.

2023-06-16 09:43 UTC, Mtze commented on app.py
> +import pyris.routes.llm
In general I think you should have all imports at the top of the file.

2023-06-16 09:43 UTC, Mtze commented on pyris/routes/llm.py
> +@app.route("/send-message", methods=["POST"])
From an API Design standpoint you should consider 
- getting rid of the verb in the route. 
- add an api version 

I suggest to use `POST /api/v1/message` as route

2023-06-16 09:53 UTC, pal03377 requested changes
The code itself looks really good, well done!

I have three points to take into consideration (non-blocking, just for discussion for you internally):
1. You are using Flask + Pydantic. You might get a lot of value by deciding for [FastAPI](https://fastapi.tiangolo.com/lo/) early instead. FastAPI includes pydantic already, it's a bit faster and newer (still mature IMO) and it works pretty much like Flask - there wouldn't be too much refactoring needed here.
2. Consider using [poetry](https://python-poetry.org/) for dependency management. The requirements.txt are a bit hard to manage over time in my experience.
3. It would be nice to have some minimal documentation on how to run this (some README with the commands to create the venv and install & run the code would suffice for now)

Nice future work: Adding a CI pipeline for automatically running the tests

Please not that I don't have deep knowledge about Iris, so I just tested running the server locally

2023-06-16 09:53 UTC, pal03377 commented on tests/routes/conftest.py
> +            yield testing_client
Could be rewritten as `with app.test_client() as testing_client, app.app_context():` (optional IMO)

2023-06-16 09:53 UTC, pal03377 commented on app.py
> +import pyris.routes.llm
This is a cyclic import. It would be better to use something like [blueprints](https://flask.palletsprojects.com/en/2.3.x/blueprints/) and importing it in one direction only instead (I think something similar is available for FastAPI). Alternatively, you could do this import somewhere else maybe 🤔

2023-06-16 09:53 UTC, pal03377 commented on pyris/services/guidance_wrapper.py
> +class GuidanceWrapper:
I am missing some docstring here. I don't really understand the purpose of this class from its name tbh

2023-06-16 09:57 UTC, pal03377 commented
Also, I would like to have some documentation on how to run tests. I got this warning when running `python -m pytest`:
```
================================================================================================= warnings summary =================================================================================================
.venv/lib/python3.8/site-packages/_pytest/config/__init__.py:1302
  /Users/paul/Sync/main/projects/Iris/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py:1302: PytestConfigWarning: Unknown config option: env_files

    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

2023-06-16 09:58 UTC, Hialus commented
> Nice future work: Adding a CI pipeline for automatically running the tests

I'll add some GitHub Actions workflows for deployments and can then also add workflows to automatically run the tests 👍🏻

2023-06-16 10:40 UTC, Kroko-fant requested changes

2023-06-16 10:40 UTC, Kroko-fant commented on pyris/services/guidance_wrapper.py
> +    def __init__(self, model: LLMModel, handlebars: str, parameters: dict = {}) -> None:
parameters : dict {} is mutable which should not be the case as it can lead to bugs in some cases.

The following would put {'foo': 'baa'} in when the class gets initialized the second time :D
```py
class A:
    def __init__(self, default_arg :dict = {}):
        print(default_arg)
        default_arg["foo"] = "baa"
```



This would be a simple fix for 
```py
     def __init__(self, model: LLMModel, handlebars: str, parameters=None) -> None:
        if parameters is None:
            parameters = {}
        self.model = model
        self.handlebars = handlebars
        self.parameters = parameters
 ```

2023-06-16 15:09 UTC, dakennguyen commented on app.py
> +import pyris.routes.llm
this is resolved when I changed to FastAPI :)

2023-06-16 15:09 UTC, dakennguyen commented on pyris/routes/llm.py
> +@app.route("/send-message", methods=["POST"])
good idea, thank you!

2023-06-16 15:13 UTC, dakennguyen commented on tests/routes/conftest.py
> +            yield testing_client
this is resolved when I changed to FastAPI :) and thank you for suggesting FastAPI, and I even prefer it better since I also have more experience in FastAPI than Flask

2023-06-16 15:14 UTC, dakennguyen commented on pyris/services/guidance_wrapper.py
> +class GuidanceWrapper:
I added docstrings

2023-06-16 15:35 UTC, dakennguyen commented
> Also, I would like to have some documentation on how to run tests. I got this warning when running `python -m pytest`:
> 
> ```
> ================================================================================================= warnings summary =================================================================================================
> .venv/lib/python3.8/site-packages/_pytest/config/__init__.py:1302
>   /Users/paul/Sync/main/projects/Iris/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py:1302: PytestConfigWarning: Unknown config option: env_files
> 
>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> ```

Hi, this one should be resolved now with poetry. I also updated the README for the instructions

2023-06-16 22:39 UTC, Kroko-fant commented on pyris/services/guidance_wrapper.py
> +    def __init__(self, model: LLMModel, handlebars: str, parameters: dict = {}) -> None:
that should work 👍

2023-06-17 13:21 UTC, Hialus requested changes

2023-06-17 13:21 UTC, Hialus commented on .env.test
Since this env file is identical to the example env file and only used for testing you should do one of the following:
- Remove one of them
- Move this file to the test directory

2023-06-17 13:21 UTC, Hialus commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
You should proably put something here. Maybe ask Patrick what the authors should be. (I'd guess that it is the chair)

2023-06-17 23:47 UTC, dakennguyen commented on .env.test
they're the same now but may not be the same in the future. For example,  we want to recommend dev to use some SMTP mail provider, so we put it in the .env.example. But running tests may need to provide something else. And I think we should put every dotenv files in the same folder

However, I'm gonna migrate to use yml settings anyway, so probably these files will be deleted in the next PR

2023-06-17 23:57 UTC, dakennguyen commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
Patrick said we will put the names of those who actually write code in the project, so I put my name here first and you can also do this in your PR :D

2023-06-18 13:44 UTC, Hialus requested changes
Tried to test it with the Artemis connector and found these two issues with the DTOs

2023-06-18 13:44 UTC, Hialus commented on app/models/dtos.py
> +    GPT35_TURBO = "gpt-3.5-turbo"
This does not match the enum in Artemis:
```suggestion
    GPT35_TURBO = "GPT35_TURBO"
```

2023-06-18 13:44 UTC, Hialus commented on app/models/dtos.py
> +        template: str
This also does not match the Artemis implementation
```suggestion
        id: int
        content: str
```

2023-06-18 15:18 UTC, Hialus commented on app/services/guidance_wrapper.py
> +            model=self.model.value,
This should probably also be a part of the settings.

2023-06-18 15:23 UTC, pal03377 requested changes
I also have a few new code comments. Other than those, well done!

2023-06-18 15:23 UTC, pal03377 commented on app/core/custom_exceptions.py
> +            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
Why not use an error code of 400 directly? 🤔

2023-06-18 15:23 UTC, pal03377 commented on app/models/dtos.py
> +    message: Message
I believe that the variables here are camelCased because of an interface to Artemis (which uses this convention), but for Python variable names, the convention usually is to snake_case everything. You might want to ignore that convention and use camelCase everywhere to avoid problems, but this should be as consistent as possible.

2023-06-18 15:23 UTC, pal03377 commented on app/services/guidance_wrapper.py
> +        self, model: LLMModel, handlebars: str, parameters: dict = {}
Here's another case of the mutable default dict, which often causes hard-to-debug problems

2023-06-18 15:23 UTC, pal03377 commented on app/services/guidance_wrapper.py
> +            raise ValueError("The parameters miss required keys")
Why not keep a `KeyError` here?

2023-06-18 16:09 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +        self, model: LLMModel, handlebars: str, parameters: dict = {}
@pal03377 do you mean the `parameters`? I use `self.parameters = MappingProxyType(parameters)`, so people can't modify `self.parameters` anymore, shouldn't it solve the problem?

2023-06-18 16:12 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +            model=self.model.value,
it should be when I change to use yml configuration, then we will indicate one model by the yml key. Right now `self.model` is the input for this service, so we can select different models

2023-06-18 16:22 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +            raise ValueError("The parameters miss required keys")
because with KeyError I'll have something like this when I use `BadDataException` (there a single quote inside `msg`):
```python
{
	"detail": [
		{
			"loc": [],
			"msg": "'The parameters miss required keys'",
			"type": "value_error.bad_data"
		}
	]
}
```
And with ValueError:
```python
{
	"detail": [
		{
			"loc": [],
			"msg": "The parameters miss required keys",
			"type": "value_error.bad_data"
		}
	]
}
```
In the client perspective, I think it doesn't help to distinguish between KeyError or ValueError, but dealing with the extra single quote may be not nice

2023-06-18 16:25 UTC, dakennguyen commented on app/models/dtos.py
> +    message: Message
`preferred_model: LLMModel = Field(..., alias="preferredModel")`
I can do something like this

2023-06-18 16:43 UTC, dakennguyen commented on app/core/custom_exceptions.py
> +            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
do you mean change 422 to 400? Or we don't need to define BadDataException here?

2023-06-18 17:42 UTC, pal03377 commented on app/core/custom_exceptions.py
> +            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
I mean directly using something like `raise HTTPException(status_code=400, detail="Bad data")` and not defining this here

2023-06-18 17:49 UTC, pal03377 commented on app/services/guidance_wrapper.py
> +        self, model: LLMModel, handlebars: str, parameters: dict = {}
I think this doesn't really work, as the `types` package only provides types that don't change functionality to my knowledge. I think you'll need to do something like `parameters = None` and then `if parameters is None: parameters = {}`. It's sadly a bit strange in Python

2023-06-18 17:49 UTC, pal03377 commented on app/services/guidance_wrapper.py
> +            raise ValueError("The parameters miss required keys")
Oh, interesting!

2023-06-18 17:49 UTC, dakennguyen commented on app/core/custom_exceptions.py
> +            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
@pal03377 I want to have similar structure to pydantic. Pydantice response is like [this](https://github.com/ls1intum/Pyris/blob/ed37a71c35b0346388a38493d381c5d081d3ca1a/tests/routes/messages_test.py#L45-L63). While HTTPexception is like this:
```
{
	"detail": "Bad data"
}
```
not really important but I think it's just nicer :D

2023-06-18 17:49 UTC, pal03377 commented on app/services/guidance_wrapper.py
> +            raise ValueError("The parameters miss required keys")
For some reason I cannot resolve this, but feed free to consider this thread resolved

2023-06-18 17:50 UTC, pal03377 commented on app/core/custom_exceptions.py
> +            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
Ok, I'm also fine with this 👍

2023-06-18 18:58 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +        self, model: LLMModel, handlebars: str, parameters: dict = {}
seems like it the state of the art rn. I changed as suggested!

2023-06-18 20:16 UTC, Hialus commented on app/services/guidance_wrapper.py
> +            raise ValueError("The parameters miss required keys")
But the data from the KeyError is lost like this isn't it? At least during my testing I had to print the KeyError, so I could see what was wrong.

2023-06-18 20:16 UTC, Hialus commented on app/routes/messages.py
> +def send_message(body: SendMessageRequest) -> SendMessageResponse:
This method is missing token authentication currently. Do you plan to add this in a follow up? Without it, we can't deploy it to a VM.

2023-06-18 20:59 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +            raise ValueError("The parameters miss required keys")
okay if it's necessary, I'll leave the exception as is. The error now would be like this:
```
{
	"detail": [
		{
			"loc": [],
			"msg": "\"Command/variable 'query' not found! Please pass it when calling the program (or set a default value for it when creating the program).\"",
			"type": "value_error.bad_data"
		}
	]
}
```

2023-06-18 20:59 UTC, dakennguyen commented on app/routes/messages.py
> +def send_message(body: SendMessageRequest) -> SendMessageResponse:
yess, I'll add in another PR because adding more stuff to this PR will just prolong the feedback loop I think

2023-06-19 09:01 UTC, Hialus approved these changes
All my concerns regarding the functionality have been addressed or will be in a future PR.
Interfacing with Pyris from Artemis now works as expected 👍🏻 

If some of the other reviewers give the code their approval we can get this merged. 🚀

2023-06-19 18:49 UTC, pal03377 approved these changes
All my code comments have been addressed. Solid start for this repo! 💪

2023-06-19 22:19 UTC, merged