`Development`: Improve LLM handling in Pyris
ls1intum/Pyris pull request #12
Opened 2023-07-12 12:51 UTC by Hialus

This PR adds the following:
- Possibility to have multiple API tokens
- Possibility to add new LLM in the application.yml without requiring changes to the code
- New endpoint to get all available models (for a token)
- Changes to the messages endpoint to use this system

2023-07-12 18:11 UTC, dakennguyen commented on app/routes/models.py
> +    api_key_config: APIKeyConfig = Depends(TokenValidator()),
could u check if `TokenValidator` is run once or twice?

2023-07-12 18:11 UTC, dakennguyen commented on app/dependencies.py
> +        self, request: StarletteRequest, api_key: str = Depends(_get_api_key)
unused `request`

2023-07-12 18:11 UTC, dakennguyen commented on app/routes/messages.py
>          raise InvalidModelException(str(e))
we already check this condition in `TokenPermissionsValidator`, so I think we can omit either of them. And because `preferred_model` field is really relevant to this endpoint only, then I guess the `TokenPermissionsValidator` is not really necessary?

2023-07-16 21:32 UTC, Hialus commented on app/routes/models.py
> +    api_key_config: APIKeyConfig = Depends(TokenValidator()),
Good catch. It was called twice, so I remove one of them.

2023-07-16 21:34 UTC, Hialus commented on app/routes/messages.py
>          raise InvalidModelException(str(e))
We actually don't. `TokenPermissionsValidator` just checks if the provided API key has an entry matching the requested model. Here we actually get the model from the config and it is theoretically possible that the config is invalid and there is no model with the specific `preferred_model` key, despite the key having it listed. This is a very rare case, so this is mostly just a safe guard.

2023-07-17 11:36 UTC, dakennguyen requested changes

2023-07-17 11:36 UTC, dakennguyen commented on tests/routes/messages_test.py
> +config.settings.pyris.api_keys = [api_key_config]
if we run the whole test suite, this config will apply to all other test files right? I think it's a better idea to use fixture, so we can control which test will use what setting

2023-07-17 13:53 UTC, Hialus commented on tests/routes/messages_test.py
> +config.settings.pyris.api_keys = [api_key_config]
I don't really know anything about testing in Python. Since it works like this I'd leave it for now unless you want to fix it yourself.

2023-07-17 19:12 UTC, dakennguyen commented on tests/routes/messages_test.py
> +config.settings.pyris.api_keys = [api_key_config]
it could be addressed later

2023-07-17 19:12 UTC, dakennguyen approved these changes

2023-07-18 11:02 UTC, greekgeek1 approved these changes

2023-07-18 11:33 UTC, DemjenDavid approved these changes

2023-07-18 12:56 UTC, merged