`Pipeline`: Add lecture chat pipeline connection
ls1intum/Pyris pull request #173
Opened 2024-11-11 16:25 UTC by sebastianloose

Add a POST route to connect the lecture chat pipeline, enabling Artemis to send messages directly into the lecture chat system.

2024-11-19 09:49 UTC, iyannsch requested changes

2024-11-19 09:49 UTC, iyannsch commented on app/vector_database/lecture_schema.py
> +        # )
Just as code rabbit pointed out, do we still need this? As this condition is only triggered when the `LectureSchema.COLLECTION_NAME` exists in the collection, you can be sure that the returned `collection != null`. Do you want to overwrite it or not?

2024-11-19 09:49 UTC, iyannsch commented on app/web/routers/pipelines.py
> +            run_id=dto.settings.authentication_token,
Might not be your code, but it seems a bit sketchy that something as confidential as a `authentication token` is used for a less-confidential context such as a random `callback id` 😅 Is it supposed to be like this?

2024-11-19 09:49 UTC, iyannsch commented on app/web/routers/pipelines.py
> +    thread = Thread(target=run_lecture_chat_pipeline_worker, args=(dto, variant))
The order of arguments is flipped in this POST endpoint: First `variant`, second `dto`. In the internal methods you use the flipped order. I'd be happy if you could decide and align to one way of doing it ☺️

2024-11-27 19:15 UTC, bassner commented on app/web/routers/pipelines.py
> +            run_id=dto.settings.authentication_token,
Sounds weird but yes. The token is unique per job

2024-11-27 19:23 UTC, bassner submitted a review, later dismissed

2024-11-27 19:45 UTC, merged