feature/add dockerfile
ls1intum/Pyris pull request #2
Opened 2023-06-17 10:55 UTC by dakennguyen

2023-06-17 12:50 UTC, Hialus requested changes

2023-06-17 12:50 UTC, Hialus commented on README.md
> +- Stop server: `docker-compose down` or `task down`
`docker-compose` is deprecated. Please use `docker compose`
```suggestion
- Build docker: `docker compose build` or `task build`
- Run server: `docker compose up -d` or `task up`
- Stop server: `docker compose down` or `task down`
```

2023-06-17 12:50 UTC, Hialus commented on Taskfile.yml
> +      - docker-compose logs -f server
```suggestion
      - docker compose build

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  test:
    cmds:
      - docker compose run --rm --entrypoint="poetry run pytest" server

  format:
    aliases: [ fmt ]
    cmds:
      - docker compose run --rm --entrypoint="poetry run black ." server

  lint:
    cmds:
      - docker compose run --rm --entrypoint="poetry run flake8" server
      - docker compose run --rm --entrypoint="poetry run black . --check" server

  logs:
    cmds:
      - docker compose logs -f server
```

2023-06-17 12:50 UTC, Hialus commented on docker-compose.yml
> +      - .:/app
Why do you mount the app dir here? It should already be a part of the docker image.

2023-06-17 12:50 UTC, Hialus commented on Dockerfile
> +COPY poetry.lock pyproject.toml /app/
You also need to copy the app dir here:
```suggestion
COPY poetry.lock pyproject.toml /app/
COPY app /app/app
```

2023-06-17 13:04 UTC, dakennguyen commented on docker-compose.yml
> +      - .:/app
so the container will mount the files from our local machine. It makes life easier for dev when they change something, they don't need to rebuild the image

2023-06-17 13:05 UTC, dakennguyen commented on Dockerfile
> +COPY poetry.lock pyproject.toml /app/
this one's related to the comment above

2023-06-17 13:05 UTC, Hialus commented on docker-compose.yml
> +      - .:/app
Alright. If this also works if the files are already in the docker image then I have no problem with it.

2023-06-17 13:06 UTC, Hialus commented on Dockerfile
> +COPY poetry.lock pyproject.toml /app/
Yes, but this is acutally needed. WIthout it the build docker image is useless for production.

2023-06-17 13:10 UTC, Hialus commented on Dockerfile
> +COPY poetry.lock pyproject.toml /app/
If this is conflicting with using this image for development, you should create a separate Dockerfile for development.
The main Dockerfile should be usable for deployment.

2023-06-17 13:18 UTC, dakennguyen commented on Dockerfile
> +COPY poetry.lock pyproject.toml /app/
ah okay, should it be `COPY . /app`?

2023-06-17 13:22 UTC, Hialus commented on Dockerfile
> +COPY poetry.lock pyproject.toml /app/
No, since we don't need stuff like the `tests` directory in the docker image. 
You would either have to create a dockerignore file or only copy the relevant parts into the docker image.

2023-06-18 11:05 UTC, Hialus approved these changes
Looks good to me now. Just one uvicorn related thing, where I am not sure if this needs to be adjusted.

2023-06-18 11:05 UTC, Hialus commented on Dockerfile
> +CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
Did a quick search and it seems like you are supposed to use a different command for production environments: `gunicorn -k uvicorn.workers.UvicornWorker` and https://www.uvicorn.org/deployment/ 

I'm not familiar with uvicorn, but it would be great if you could take a look here.

2023-06-18 11:20 UTC, dakennguyen commented on Dockerfile
> +CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
👍 looks like we need to use `gunicorn -k uvicorn.workers.UvicornWorker`. I'd leave this in your PR where we can test it out if the deployment works, but you remind me that at least I should delete `--reload` here

2023-06-18 11:45 UTC, Hialus commented on Dockerfile
> +CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
Makes sense.
I've added it to my PR now and tested it locally. Feel free to take a look.

2023-06-19 22:24 UTC, Hialus approved these changes

2023-06-19 22:24 UTC, merged