Change response type to return all generated content
ls1intum/Pyris pull request #34
Opened 2023-10-09 15:23 UTC by MichaelOwenDyer

2023-10-09 15:36 UTC, MichaelOwenDyer commented
Tried running the formatter but can't seem to get the formatting checks to pass

2023-10-11 13:36 UTC, dakennguyen commented
> Tried running the formatter but can't seem to get the formatting checks to pass

you can try to run this `poetry run black .`

2023-10-11 13:54 UTC, MichaelOwenDyer commented
You're right, it will break production. There is [another PR](https://github.com/ls1intum/Artemis/pull/7352) open on Artemis to change that side as well. But it might actually be smarter to just create a /v2/ endpoint, that way this can be merged without Artemis breaking.

2023-10-11 13:57 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +        import re
one small thing is that I think we should import the library at the top of the file

https://peps.python.org/pep-0008/#imports

> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.

2023-10-12 09:21 UTC, Hialus commented
> @MichaelOwenDyer I think the endpoint POST /api/v1/messages is currently being used. Will this PR break production? Otherwise, we need to introduce POST /api/v2/messages or make sure it backward backward-compatible.

> You're right, it will break production. There is https://github.com/ls1intum/Artemis/pull/7352 open on Artemis to change that side as well. But it might actually be smarter to just create a /v2/ endpoint, that way this can be merged without Artemis breaking.

That is a great idea. I think this would make sense here for the transition phase, until Artemis Prod is updated. Then we could simply the v1 afterwards.

2023-10-12 09:29 UTC, Hialus requested changes

2023-10-12 09:29 UTC, Hialus commented on app/services/guidance_wrapper.py
> +        pattern = r'{{(?:gen|geneach|set) [\'"]([^\'"]+)[\'"]$}}'
There is a small issue I can see here:
If there is more than one space between e.g. `gen` and the name e.g. `response`(like this: `gen     response`), this is still valid syntax, but is not caught by this regex. Also is the `$` the correct thing here? According to what I found it should be used at the end of a line, which is not the case here, as it is followed by `}}`.

2023-10-12 10:53 UTC, MichaelOwenDyer commented on app/services/guidance_wrapper.py
> +        pattern = r'{{(?:gen|geneach|set) [\'"]([^\'"]+)[\'"]$}}'
Thanks for pointing this out, addressed these issues

2023-10-12 10:55 UTC, MichaelOwenDyer commented
Thanks for the reviews guys. I addressed the issues you pointed out, V1 API should be behaving equivalent to before (although the logic for getting the response variable is now local to the endpoint and not directly in the guidance wrapper). I also extended the message test to test both v1 and v2.

2023-10-13 11:23 UTC, Hialus requested changes
Very nice that you could change this to a v1/v2 split!
Code changes look good, but the linter job is currently failing. Please fix that.

2023-10-13 12:20 UTC, MichaelOwenDyer commented
You got it sir. Those dangerously long comments have been shortened.

2023-10-14 10:04 UTC, dakennguyen approved these changes
code LGTM!

2023-11-06 10:22 UTC, Hialus approved these changes
Change look good to me and since it has been deployed to the test server for some time without issues it also is sufficiently tested now.
Great job 🚀

2023-11-24 17:43 UTC, merged