Refactoring suggestions
ls1intum/Pyris pull request #59
Opened 2024-02-14 16:55 UTC by MichaelOwenDyer

I have some **suggestions** for the LLM subsystem code. @Hialus, not trying to step on your toes, every change in this PR is a personal opinion. Could be that I am missing the bigger picture with some of these things, let me know your thoughts. Here's a summary of what I did:

- Renamed classes to reflect their conceptual purpose rather than implementation-oriented. In my opinion, conceptual class names make it easier to reason about the code using those classes.
- Took out some code in `basic_request_handler` that I thought was redundant.
- In LLMManager, I replaced the linear LLM search with a dictionary lookup by ID. Even though O(n) would not be a performance bottleneck with the low amount of LLMs we have, let's do it in O(1).
- Renamed the methods `completion()`, `chat_completion()`, `create_embedding()` to `complete()`, `chat()`, and `embed()` for consistency
- Added one requirement for PyYAML since it is being used in LLMManager, and changed the requirements in `requirements.txt` to use `~=` instead of `==`.

2024-02-14 17:30 UTC, Hialus requested changes
As it stands right now you did a lot of changes in the internals of the LLM subsystem. I very clearly stated that the entire internals of the subsystem are subject to change and further improvements. The current implementation is merely a simple first version to use in the development of the pipeline subsystem.

The changes to the RequestHandler are sensible and I'd suggest we implement them, as we already discussed that.
The changes to the LlmManager are entirely unnecessary, as the current implementation will effectively be completely replaced. As it is not part of the public API of the subsystem this is easily doable. So any changes here do not really make much sense.
For the changes about the `AbstractLlmWrapper` I'd need to spent some additional time thinking about the best possible name, but as they are internal classes this is not really high priority and can be done at any time.

Also your code fails the linter checks. I'd suggest to install the pre commit hooks.

2024-02-14 17:30 UTC, Hialus commented on app/llm/wrapper/openai_chat.py
> +class NativeOpenAIChatModel(OpenAIChatModel):
I do not think the name "Native" is a good choice here. The term suggests that this somehow calls OS native code.

2024-02-14 17:30 UTC, Hialus commented on app/llm/wrapper/openai_chat.py
> +    def model_post_init(self, __context: Any):
This is the official Pydantic method declaration, so I wanted to keep it like that.

2024-02-14 17:30 UTC, Hialus commented on requirements.txt
This is probably a very opinion based thing, but I prefer to pin the version, so that we can be sure that no matter when the program is run it will use the exact same dependencies.

2024-02-15 09:32 UTC, MichaelOwenDyer commented on app/llm/basic_request_handler.py
> -                f"The LLM {llm.__str__()} does not support completion"
The default implementations in `model.py` contain the reason

2024-02-15 09:36 UTC, MichaelOwenDyer commented on app/llm/wrapper/openai_chat.py
> +class NativeOpenAIChatModel(OpenAIChatModel):
I would like to just name this `OpenAIChatModel`, but that's the name of the superclass. Changed to `DirectOpenAIChatModel`.

2024-02-16 17:05 UTC, merged