Fix content in response
ls1intum/Pyris pull request #6
Opened 2023-06-23 16:08 UTC by Hialus

2023-06-23 21:48 UTC, dakennguyen requested changes

2023-06-23 21:48 UTC, dakennguyen commented on app/models/dtos.py
> +        content: list[Content]
```suggestion
        contents: list[Content]
```
because it's a list I would suggest to use plural

2023-06-23 21:48 UTC, dakennguyen commented on app/routes/messages.py
> +        content = [content]
the `guidance.query()` always returns 1 Content only, why don't we let Artemis wrap it into an array if that is what it needs? If we really want to make an array here, then I would suggest to wrap it in the `GuidanceWrapper`

```
return [Content(type=ContentType.TEXT, textContent=result["response"])]
```

2023-06-23 22:43 UTC, Hialus commented on app/routes/messages.py
> +        content = [content]
In the future I might experiment with returning either multiple responses in a single template or split up the response into text, code, etc. So this way it would support that in the future as well.

2023-06-23 22:43 UTC, Hialus commented on app/models/dtos.py
> +        content: list[Content]
This is how Artemis uses it, so it has to be like this here as well.

2023-06-24 10:56 UTC, dakennguyen approved these changes

2023-06-24 14:12 UTC, merged