feature/pipeline-subsystem-v1
ls1intum/Pyris pull request #60
Opened 2024-02-15 00:10 UTC by kaancayli

2024-02-15 01:34 UTC, Hialus requested changes
Sorry for leaving so many small comments 😅. But I think they should make the code quality better.
Also please ensure that in the future not all pipelines are in the same file, but are properly split up into multiple files according to their area. Having it all in one file eventually results in an unreadable mess.

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +        return f"{self.__class__.__name__} {self.name if self.name is not None else id(self)}"
This does not seems like a valid `__repr__` implementation. This method should return a string which, when executed via e.g. `eval` would construct an instance of this object. Therefore it should return a string in the form `ClassName(param1, param2, ...)`

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +        return f"{self.__class__.__name__} {self.name if self.name is not None else id(self)}"
I think implementing a specific `__str__` for each sub-class might make more sense, as it would allow you to provide tailored information.

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +    def run(self, *args, **kwargs) -> IrisMessage:
Do you need `*args` here? `*args` is effectively a Java varargs argument and simply contains an array of unnamed values. Usually having only `**kwargs` makes more sense.

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +    def run(self, *args, query: IrisMessage, **kwargs) -> IrisMessage:
As you do not need the `*args` here, you could just leave them out.

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +    def __init__(self, llm, name=None):
What type should `llm` have?

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +class SimplePipeline(AbstractPipeline):
Please add the attributes of an object to the class scope (like in java), so that it is clearer what attributes the class has.

2024-02-15 01:34 UTC, Hialus commented on app/pipeline/pipeline.py
> +class AbstractPipeline(metaclass=ABCMeta):
Please add the attributes of an object to the class scope (like in java), so that it is clearer what attributes the class has.

2024-02-15 02:05 UTC, kaancayli commented on app/pipeline/pipeline.py
> +        return f"{self.__class__.__name__} {self.name if self.name is not None else id(self)}"
I didn't know that . Thanks for the comment

2024-02-15 02:07 UTC, kaancayli commented on app/pipeline/pipeline.py
> +    def run(self, *args, **kwargs) -> IrisMessage:
The idea was to have a method signature that is as general as possible. If you think, we don't require unnamed arguments, they can be removed

2024-02-19 09:12 UTC, MichaelOwenDyer submitted a review, later dismissed
looks good to me

2024-02-21 13:52 UTC, Hialus requested changes
Code looks mostly good, just 3 suggestions :D

2024-02-21 13:52 UTC, Hialus commented on app/common/singleton_abstract.py
Remove this unused class

2024-02-21 13:52 UTC, Hialus commented on app/pipeline/pipeline.py
> +    def __call__(self, **kwargs):
Maybe also add a `__subclasshoook__` method to check that subclasses implement this method. You can see an example of this in the `llm/external/model.py` file.

2024-02-21 13:52 UTC, Hialus commented on app/pipeline/shared/summary_pipeline.py
> +    def __init__(self, llm: IrisLangchainChatModel):
Maybe a completion model may make sense here?

2024-02-21 17:33 UTC, Hialus approved these changes

2024-02-21 17:33 UTC, merged