feature/checkhealth endpoint
ls1intum/Pyris pull request #7
Opened 2023-06-24 02:15 UTC by dakennguyen

- Add health endpoint
- Protect function call with circuit breaker

2023-06-24 16:01 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +
I need to add this because when mocking `__new__` I got this problem https://github.com/pytest-dev/pytest/discussions/8009
If anyone knows a better way to mock, I would be really appreciated :)

2023-07-10 08:43 UTC, fschoenberger requested changes
Looks good so far, I have some feedback regarding the way the TTL is handled.

2023-07-10 08:43 UTC, fschoenberger commented on app/services/circuit_breaker.py
> +            ...
Is this valid python? It seems like there's some error handling missing.

2023-07-10 08:43 UTC, fschoenberger commented on app/services/circuit_breaker.py
> +    STATUS_CACHE_CLOSED_TTL = 300
It would be nice if there was somewhere documentation on the unit of the TTL. Is it milliseconds, seconds, minutes, ...?

2023-07-10 08:43 UTC, fschoenberger commented on app/services/cache.py
> +    def expire(self, key, ex):
Again, it would be nice to have an indication of the time unit used.

2023-07-10 14:44 UTC, dakennguyen commented on app/services/circuit_breaker.py
> +            ...
it is, it's called Ellipsis. I actually don't know what is the difference between `...` and `pass`, so I just use either of them

2023-07-10 16:58 UTC, dakennguyen commented on app/services/cache.py
> +        ttl = self._cache.get(f"{key}:ttl")
👍 I went with the initial option for simplicity but using dict is definitely more thorough

2023-07-11 09:25 UTC, fschoenberger commented on app/services/circuit_breaker.py
> +            ...
Would it make sense to set `is_up` in case of an exception? At the very least we should probably log that an exception occured if we're not doing any other kind of error handling.

2023-07-11 13:39 UTC, fschoenberger commented on app/services/circuit_breaker.py
> +            ...
> `is_up` will be `False` in case of exception already, or do you mean something else?

Right, sorry, I missed that. Looks good.

2023-07-16 10:34 UTC, dakennguyen commented
> Another thing that came up in conversation: Currently upon production deployment each worker is forked and thus we don't have shared state between the workers (in other words: Each worker gets its own copy of the in-memory cache).
> 
> This [can be avoided](https://stackoverflow.com/a/66135571/11988044) by using the [`--preload` flag](https://docs.gunicorn.org/en/stable/settings.html#preload-app) for the server and using [`multiprocessing.Manager`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Manager) to get a dict that's shared between workers. This is extremly important to do, otherwise the whole endeavour becomes a bit pointless.

In this link, the author comment a disclaimer himself
> Note: I do not make any claims about thread / async safety here and this method should probably not be employed in production services. In case of any doubt you should always rely on a proper database / caching / memory store solution for production setups. I myself only use this in demo code!

so I think I'm going with the Hazelcast solution since it is already well-defined. The stack also complies with Artemis

2023-07-16 19:21 UTC, fschoenberger submitted a review, later dismissed
Lgtm

2023-07-18 12:22 UTC, fschoenberger submitted a review, later dismissed

2023-07-19 08:25 UTC, FelixTJDietrich approved these changes
Code mostly LGTM, I just have two remarks.

2023-07-19 08:25 UTC, FelixTJDietrich commented on app/services/cache.py
> +    def set(self, name: str, value, ex: Union[int, None] = None):
You could use `Optional[int]` here, and also below. I think it is easier to read that way.

2023-07-19 08:25 UTC, FelixTJDietrich commented on app/services/guidance_wrapper.py
> +        return content == "1"
Is there no better way than calling the LLM to check its health?
Maybe like `openai.Deployment.list()`?

But I guess doing inference on it is a sure way of finding out 😅

2023-07-19 09:05 UTC, dakennguyen commented on app/services/cache.py
> +    def set(self, name: str, value, ex: Union[int, None] = None):
thank you, that's a good suggestion :)

2023-07-19 09:11 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +        return content == "1"
I couldn't find any other way and tbh I find guidance's [docs](https://github.com/microsoft/guidance/blob/main/notebooks/tutorial.ipynb) hard to find information

I got this error with your suggestion
```
openai.error.APIError: Deployment operations are only available for the Azure API type.
```

2023-07-19 10:50 UTC, FelixTJDietrich commented on app/services/guidance_wrapper.py
> +        return content == "1"
I mean, I guess you guys are using the OpenAI models hosted on Azure in production. You have to set the openai library credentials first.

2023-07-19 12:12 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +        return content == "1"
but this approach will be tied to OpenAI right? I think our purpose of using guidance is to let it handle requests for us, no matter if we are using OpenAI or something else in the future

2023-07-19 12:22 UTC, Hialus commented on app/services/guidance_wrapper.py
> +        return content == "1"
Its already tied to OpenAI with `guidance.llms.OpenAI.cache.clear()`.
Ideally, we would decouple this and then make it simple to add support for other LLM types with the strategy pattern. The current solution could be the fallback and then we add specialized health checks on top of it.

2023-07-19 12:25 UTC, dakennguyen commented on app/services/guidance_wrapper.py
> +        return content == "1"
cool, let's improve it in another PR. I think we can keep the scope as is now :)

2023-07-22 14:03 UTC, bassner approved these changes

2023-07-22 14:04 UTC, merged