Feature/fast api integration
ls1intum/Pyris pull request #70
Opened 2024-02-28 14:34 UTC by MichaelOwenDyer

2024-02-28 14:47 UTC, Hialus requested changes

2024-02-28 14:47 UTC, Hialus commented on app/web/routers/pipelines.py
> +    pipeline(dto=dto)
I see 2 problems here:
1. You do not do any authentication to ensure that the incoming request is from Artemis. You can reuse the token auth from PyrisV1 here
2. You do not seem to start the pipeline in a separate thread, which would make this is blocking call, which we want to avod.

2024-02-28 14:47 UTC, Hialus commented on app/web/status/status_update.py
> +        url = f"/api/v1/public/pyris/tutorchat/runs/{run_id}/status"
This URL is missing the protocol & domain in front. This should be extracted from the settings DTO that Artemis gives you.

2024-02-28 14:47 UTC, Hialus commented on .gitignore
> +/app/pipeline_playground.py
Not sure if this should be added here. I'd rather opt for an entire folder or just add this to your local only git ignore

2024-03-05 15:55 UTC, kaancayli commented on app/pipeline/chat/tutor_chat_pipeline.py
> +        self.callback.on_status_update(status_dto)
We will do our own end to end testing after we deploy the application.

2024-03-06 00:30 UTC, kaancayli commented on README.MD
> +TBD
Docker setup is yet to be merged. It waits this pull request to be merged. After it's merged, we will have a more clear picture regarding docker setup instructions.

2024-03-06 21:03 UTC, kaancayli commented on app/pipeline/chat/tutor_chat_pipeline.py
> +        self.pipeline = self.llm | StrOutputParser()
For this pipeline we currently use gpt35. We do not use environment variables for default model names.

2024-03-06 21:04 UTC, kaancayli commented on app/pipeline/chat/tutor_chat_pipeline.py
> +
Addressed in the next commit.

2024-03-11 12:23 UTC, Hialus commented on app/common/custom_exceptions.py
> +                "type": "not_found",
Please be more specific with the types. E.g. "pipeine_not_found", so Artemis can clearly distingush between them

2024-03-11 12:29 UTC, Hialus commented
str | None in the DTOs to Optional. See also https://stackoverflow.com/questions/69440494/python-3-10-optionaltype-or-type-none

2024-03-11 12:35 UTC, Hialus commented
Merge MessageDTO and IrisMessage into one PyrisMessage class

2024-03-11 12:40 UTC, Hialus commented on app/domain/health_status_dto.py
Remove all health related stuff

2024-03-11 13:09 UTC, kaancayli commented on app/web/data/repository_fetch.py
Delete this.

2024-03-11 13:09 UTC, kaancayli commented on app/web/routers/health.py
> +def health_check():
Returon 200 and do auth check

2024-03-11 13:09 UTC, kaancayli commented on app/web/routers/models.py
Delete this.

2024-03-11 13:09 UTC, Hialus commented
Comments will be adressed in future PRs.

2024-03-12 03:37 UTC, merged