Add Image support to llm
ls1intum/Pyris pull request #89
Opened 2024-03-31 20:27 UTC by yassinsws

Motivation
In the future we want to support images in our LLM subsystem. This PR aims to introduce support for this.

Description
To add support for Images I added a new domain model PyrisImage to represent images in a unified way.
I also added a basic wrapper for OpenAIs Dall-E to showcase how images can be created.
I also added support to pass images to Ollama models via normal and chat completion.
I also added support for OpenAI GPT4-Vision models

2024-04-08 07:15 UTC, Hialus commented on app/llm/external/model.py
>          """Create a completion from the prompt"""
Not sure why you change this. Ollama definitley supports images in completion mode

2024-04-25 20:37 UTC, Hialus requested changes
When starting I get this warning:
> pyris-app  | /usr/local/lib/python3.12/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
pyris-app  | * 'schema_extra' has been renamed to 'json_schema_extra'
pyris-app  |   warnings.warn(message, UserWarning)

I also tested this on pyris-test and TS5 and the tutor chat still works.
Please fix the warning and merge main, then this can get merged.

2024-04-25 20:41 UTC, kaancayli requested changes
You need to solve the merge conflicts. We renamed the `IrisMessage` to `PyrisMessage` and also adjusted the llms accordingly. If you have question ask me anytime.

2024-04-25 21:48 UTC, kaancayli requested changes

2024-04-25 21:48 UTC, kaancayli commented on app/domain/iris_message.py
`IrisMessage` is replaced with `PyrisMessage`. You may want to remove this.

2024-04-25 23:46 UTC, Hialus requested changes
It seems like a lot of this PR went missing when you merged main: 
- GPT4 Vision is no longer supported
- Ollama no longer supports images
- and probably a little more
Please fix this..

2024-04-25 23:46 UTC, Hialus commented on app/domain/iris_message.py
Why do you add this? We use `PyrisMessage` now

2024-04-27 01:59 UTC, Hialus requested changes
Went through the code and there were a couple of issues (Ollama did not work, only the first content of a message was used, ...). I already fixed most of them in  [001b99d](https://github.com/ls1intum/Pyris/pull/89/commits/001b99d118c4fcb244c2c0a64f53a179de088166)

Though I do have some more smaller questions.

2024-04-27 01:59 UTC, Hialus commented on app/domain/data/image_message_content_dto.py
> +        }
We do not do this for any other model. Why is this needed here?

2024-04-27 09:20 UTC, kaancayli approved these changes

2024-04-27 15:18 UTC, yassinsws commented on app/domain/data/image_message_content_dto.py
> +    base64: List[str] = Field(..., alias="base64")  # List of base64-encoded strings
You can have one message with multiple images. That's how it works in the openAI API call at least, so I think it makes more sense to have the list there. 
Other that that I will erase the alias, thanks

2024-04-27 15:21 UTC, yassinsws commented on app/domain/data/image_message_content_dto.py
> +        }
it is not necessary it can be erased but it also serves as documentation. Will erase it to keep the DTOs consistent

2024-04-27 15:26 UTC, kaancayli submitted a review, later dismissed
code

2024-04-27 19:30 UTC, Hialus commented on app/llm/external/openai_dalle.py
> +        )
This does not work, because `ImageMessageContentDTO.base64` is an array.

2024-04-27 19:31 UTC, Hialus commented on app/domain/data/image_message_content_dto.py
> +    base64: List[str] = Field(..., alias="base64")  # List of base64-encoded strings
You actually do not use this for the OpenAI API in any way. The only place where this would make sense is the Dalle model, as that returns multiple images, but even there you simple create separate `ImageMessageContentDTO`.
As it currently stands you could simply make this a single string and it would not really change anything behavior wise and would make things easier to handle.

2024-04-27 19:31 UTC, Hialus requested changes
The black linter is failing

2024-04-27 20:07 UTC, yassinsws commented on app/domain/data/image_message_content_dto.py
> +    base64: List[str] = Field(..., alias="base64")  # List of base64-encoded strings
Nope this would be used for image interpretation(This can be useful for example for future interpretation of the lecture, if you have multiple pages where they have diagrams and you want them to be interpreted together)

2024-04-27 20:14 UTC, Hialus commented on app/domain/data/image_message_content_dto.py
> +    base64: List[str] = Field(..., alias="base64")  # List of base64-encoded strings
Yes, but you could simply use multiple message contents for that. That way (at least with GPT4V) you also can have text in between the images, instead of just having a bunch of images after one another.

2024-04-28 17:24 UTC, yassinsws commented on app/domain/data/image_message_content_dto.py
> +    base64: List[str] = Field(..., alias="base64")  # List of base64-encoded strings
I think both versions make sense but let's do it in a simple text as it does not hinder the work for now.

2024-04-29 10:55 UTC, Hialus approved these changes

2024-04-29 10:55 UTC, merged